### ISSUE TITLE
Switch all admin storage to MySQL

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/TotalFreedomMod#1]
To make Icarus able to properly work how we want it to work, we will need to change TFM to store admin information in MySQL instead of YAML

**Comment by WickedGamingUK** [comment]
This should be quite a simple task. Make sure to use prepared statements and JDBLib ;)

**Comment by Wild1145** [comment]
If its so simple your welcome to do it yourself @WickedGamingUK  :P

**Comment by WickedGamingUK** [comment]
@Wild1145 Nah, I've got enough to do.

**Comment by Wild1145** [comment]
We are just going to move Admin Management to IcarusMod instead.
